apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-nginx-multicluster
  namespace: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-nginx-multicluster
  template:
    metadata:
      labels:
        app: poc-nginx-multicluster
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

