apiVersion: v1
kind: Service
metadata:
  name: nginx-service-alt
  namespace: poc-multicluster
spec:
  selector:
    app: nginx-alt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP